name: Run DevOps Test

on:
  push:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    name: Execute RPT test suite
    steps:
      - name: Trigger DevOps Test Hub
        uses: Rational-Software/testhub-github-action@v1.1
        with:
          serverURL: https://testhub.sbx0003.play.hclsofy.com
          offlineToken: ${{ secrets.TESTHUB_TOKEN }}
          teamspace: "Initial"
          project: "HCL-DevOps-Test-Hub-First-Project"
          branch: "main"
          assetId: "Tests/demo1.testsuite"

